baseurl = "https://strativerse.dunnington.ca/"
languageCode = "en-us"
title = "Strativerse"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[outputs]
  home = [ "HTML", "JSON" ]
  section = ["HTML", "JSON"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Records"
    url = "/record/"
    weight = 10
    
[[menu.main]]
    name = "Features"
    url = "/feature/"
    weight = 20

[[menu.main]]
    name = "Parameters"
    url = "/parameter/"
    weight = 30

[[menu.main]]
    name = "Publications"
    url = "/publication/"
    weight = 40

[[menu.main]]
    name = "People"
    url = "/person/"
    weight = 50

[params]
    description = "A collection of time-stratigraphic records."

    # path to the favicon, under "static"
    favicon = "images/logo.png"
    
    gitHubRepo = "paleolimbot/strativerse-hugo"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
    
[taxonomies]
    publication = "publications"
    parameter = "parameters"
    person = "people"
    record = "records"
    feature = "features"
